version: "3.1"
services:
  server:
    build:
      context: .docker/Nginx
    restart: 'no'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./source/public:/var/www/html/public
      - ./.docker/Nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/log/nginx/
    depends_on:
      - api
  api:
    build:
      context: .docker/Api
    restart: "no"
    depends_on:
      - db
      - redis
    volumes:
      - ./source:/var/www/html
      - ./.docker/Api/Config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/Api/Config/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    ports:
      - 9001:9000
  db:
    build:
      context: .docker/Mysql
    restart: "no"
    volumes:
      - ./db:/var/lib/mysql
      - ./.docker/Mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-a123456}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-huydv}
      - MYSQL_USER=${MYSQL_USER:-huydv}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-a654321}
    ports:
      - 3301:3306
  redis:
    build:
      context: .docker/Redis
    volumes:
      - ./redis:/data
    restart: "no"
    ports:
    - 6379:6379
  socket:
    build:
      context: .docker/Socket
    depends_on:
      - redis
      - api
      - queue
    volumes:
      - ./source/.env:/app/.env
    restart: "no"
    ports:
      - 6001:6001
  queue:
    build:
      context: .docker/Queue
    restart: "no"
    depends_on:
      - db
      - api
      - redis
    volumes:
      - ./source:/var/www/html
      - ./source/storage/logs/supervisor:/var/log/supervisor
      - ./source/storage/logs/queue:/var/www/html/storage/logs
      - ./.docker/Queue/Config/etc/supervisor/:/etc/supervisor/conf.d
      - ./.docker/Queue/Config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/Queue/Config/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
#disk
volumes:
  dir-site:
    driver_opts:
      device: ./
      o: bind
      type: tmpfs
